import { useRouter } from 'next/router';
import { workspaceStore } from '@/store';
import { useEffect } from 'react';
import Head from 'next/head';
import BoardCard from '../../components/ui/card/BoardCard';

export default function Workspace() {
  const { workspace, fetchWorkspace } = workspaceStore();
  const router = useRouter();
  const { index } = router.query;

  useEffect(() => {
    if (index) {
      fetchWorkspace(index).then(() => {
        console.log(workspace);
      });
    }
  }, [index]);

  return (
    <>
      <Head>
        <title>Waeve - Workspace {workspace && workspace.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <h1>Workspace: {index}</h1>

        <h2>Boards</h2>
        {workspace.boards.map((board) => (
          <BoardCard board={board} key={board.id} />
        ))}
      </div>
    </>
  );
}
