import Head from 'next/head';
import Home from '@/pages/_home';
import MainLayout from '@/shared/components/layouts/MainLayout';

export default function Index() {
  return (
    <>
      <Head>
        <title>Home - Krate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout>
        <Home />
      </MainLayout>
    </>
  );
}
