logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-suggest
          uri: lb://ms-suggest
          predicates:
            - Path=/api/gen/**
          filters:
            # - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: ms-tasks
          uri: lb://ms-tasks
          predicates:
            - Path=/api/**
          filters:
            # - TokenRelay=
            - RemoveRequestHeader=Cookie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/