debug: true
server:
  port: 6060
spring:
  application:
    name: ms-tasks
  mvc:
    servlet:
      path: /api
  h2:
    console:
        enabled: true
        path: /h2
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: postgres
    password: '0430'
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
