import Head from 'next/head';
import { useEffect } from 'react';

function Home() {
    useEffect(() => {
        console.log('Home');
    }, []);

    return (
        <div className="Home">
            <Head>
                <title>Waeve - Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-grow">
                Boards
            </div>
        </div>
    );
}
export default Home;
